theme: jekyll-theme-minimal
title: LiAh Sheep
description: ''
biography: Freelancer. Currently working as a Language Engineer & Translator.
hashtags:
- technology
- language
- typefaces
- ux
- podcasts
- weather
- hongkong
- cupertino
- apple
